[package]
name = "muma-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
config = "0.13.3"
dotenv = "0.15.0"
serde = { workspace = true }
